import 'package:cloud_firestore/cloud_firestore.dart';

class PopulateShops {
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  static Future<void> addSampleShops() async {
    final shops = [
      {
        'name': 'Duka la Mama Fatma',
        'description': 'Vyakula vya kila siku, matunda, mboga na bidhaa za nyumbani',
        'address': 'Mtaa wa Msimbazi, Dar es Salaam',
        'lat': -6.7924,
        'lng': 39.2083,
        'ownerId': 'sample_owner_1',
        'ownerName': 'Fatma Hassan',
        'ownerPhone': '+255712345678',
        'type': 'grocery',
        'category': 'Grocery',
        'rating': 4.8,
        'isOpen': true,
        'isVerified': true,
        'tags': ['vyakula', 'matunda', 'mboga'],
        'whatsappNumber': '+255712345678',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'name': 'Tech Tanzania',
        'description': 'Vifaa vya elektroniki, simu, kompyuta na vifaa vya nyumbani',
        'address': 'Mtaa wa Kariakoo, Dar es Salaam',
        'lat': -6.8169,
        'lng': 39.2747,
        'ownerId': 'sample_owner_2',
        'ownerName': 'Ahmed Ali',
        'ownerPhone': '+255734567890',
        'type': 'electronics',
        'category': 'Electronics',
        'rating': 4.6,
        'isOpen': true,
        'isVerified': true,
        'tags': ['simu', 'kompyuta', 'elektroniki'],
        'whatsappNumber': '+255734567890',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'name': 'Fashion House TZ',
        'description': 'Nguo za kisasa, mavazi ya kazi na mavazi ya kawaida',
        'address': 'Mtaa wa Masaki, Dar es Salaam',
        'lat': -6.7694,
        'lng': 39.2797,
        'ownerId': 'sample_owner_3',
        'ownerName': 'Grace Mwangi',
        'ownerPhone': '+255756789012',
        'type': 'clothing',
        'category': 'Fashion',
        'rating': 4.7,
        'isOpen': true,
        'isVerified': true,
        'tags': ['nguo', 'fashion', 'mitindo'],
        'whatsappNumber': '+255756789012',
        'instagramHandle': '@fashionhouse_tz',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'name': 'Pharmacy ya Afya',
        'description': 'Dawa zote za hospitali na dawa za kienyeji',
        'address': 'Mtaa wa Upanga, Dar es Salaam',
        'lat': -6.8000,
        'lng': 39.2667,
        'ownerId': 'sample_owner_4',
        'ownerName': 'Dr. Sarah Kimaro',
        'ownerPhone': '+255778901234',
        'type': 'pharmacy',
        'category': 'Pharmacy',
        'rating': 4.9,
        'isOpen': true,
        'isVerified': true,
        'tags': ['dawa', 'afya', 'hospitali'],
        'whatsappNumber': '+255778901234',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'name': 'Hardware ya Mjini',
        'description': 'Vifaa vyote vya ujenzi, paint, mabati, saruji',
        'address': 'Mtaa wa Temeke, Dar es Salaam',
        'lat': -6.8500,
        'lng': 39.2833,
        'ownerId': 'sample_owner_5',
        'ownerName': 'Joseph Mwalimu',
        'ownerPhone': '+255789012345',
        'type': 'hardware',
        'category': 'Hardware',
        'rating': 4.5,
        'isOpen': true,
        'isVerified': true,
        'tags': ['ujenzi', 'paint', 'mabati'],
        'whatsappNumber': '+255789012345',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'name': 'Beauty Palace TZ',
        'description': 'Vipodozi vya kisasa, bidhaa za ngozi na huduma za urembo',
        'address': 'Mtaa wa Oysterbay, Dar es Salaam',
        'lat': -6.7667,
        'lng': 39.2833,
        'ownerId': 'sample_owner_6',
        'ownerName': 'Amina Hassan',
        'ownerPhone': '+255790123456',
        'type': 'beauty',
        'category': 'Beauty & Cosmetics',
        'rating': 4.8,
        'isOpen': true,
        'isVerified': true,
        'tags': ['vipodozi', 'urembo', 'makeup'],
        'whatsappNumber': '+255790123456',
        'instagramHandle': '@beautypalace_tz',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'name': 'Hoteli ya Mama Lishe',
        'description': 'Chakula cha kitanzania, pilau, biryani, wali wa nazi',
        'address': 'Mtaa wa Kivukoni, Dar es Salaam',
        'lat': -6.8167,
        'lng': 39.2833,
        'ownerId': 'sample_owner_7',
        'ownerName': 'Lishe Mohamed',
        'ownerPhone': '+255701234567',
        'type': 'restaurant',
        'category': 'Tanzanian Cuisine',
        'rating': 4.6,
        'isOpen': true,
        'isVerified': true,
        'tags': ['chakula', 'pilau', 'biryani'],
        'whatsappNumber': '+255701234567',
        'createdAt': FieldValue.serverTimestamp(),
      },
    ];

    for (final shop in shops) {
      await _firestore.collection('shops').add(shop);
    }

    print('Sample shops added successfully!');
  }
}
