import 'package:flutter/material.dart';

class AppLocalizations {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'home': 'Home',
      'orders': 'Orders',
      'profile': 'Profile',
      'cart': 'Cart',
      'checkout': 'Checkout',
      'login': 'Login',
      'signup': 'Sign Up',
      'logout': 'Logout',
      'search': 'Search',
      'filter': 'Filter',
      'sort': 'Sort',
      'price': 'Price',
      'total': 'Total',
      'subtotal': 'Subtotal',
      'delivery_fee': 'Delivery Fee',
      'order_now': 'Order Now',
      'add_to_cart': 'Add to Cart',
      'remove': 'Remove',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'back': 'Back',
      'next': 'Next',
      'done': 'Done',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'no_data': 'No data available',
      'try_again': 'Try Again',
      'my_orders': 'My Orders',
      'order_history': 'Order History',
      'track_order': 'Track Order',
      'rate_order': 'Rate Order',
      'reorder': 'Reorder',
      'favorite_shops': 'Favorite Shops',
      'earnings': 'Earnings',
      'map': 'Map',
      'history': 'History',
      'account': 'Account',
      'available': 'Available',
      'my_tasks': 'My Tasks',
      'accept_order': 'Accept Order',
      'picked_up': 'Picked Up',
      'delivered': 'Delivered',
      'navigate': 'Navigate',
      'online': 'Online',
      'offline': 'Offline',
      'today_earnings': "Today's Earnings",
      'deliveries': 'Deliveries',
      'settings': 'Settings',
      'language': 'Language',
      'theme': 'Theme',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'swahili': 'Swahili',
      'english': 'English',
      'notifications': 'Notifications',
      'help': 'Help',
      'about': 'About',
      'contact': 'Contact',
      'phone': 'Phone',
      'email': 'Email',
      'address': 'Address',
      'name': 'Name',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'reset_password': 'Reset Password',
      'change_password': 'Change Password',
      'update_profile': 'Update Profile',
      'view_all': 'View All',
      'see_more': 'See More',
      'see_less': 'See Less',
      'read_more': 'Read More',
      'close': 'Close',
      'open': 'Open',
      'closed': 'Closed',
      'rating': 'Rating',
      'reviews': 'Reviews',
      'write_review': 'Write a Review',
      'submit': 'Submit',
      'share': 'Share',
      'copy': 'Copy',
      'paste': 'Paste',
      'select': 'Select',
      'select_all': 'Select All',
      'clear': 'Clear',
      'apply': 'Apply',
      'reset': 'Reset',
      'refresh': 'Refresh',
      'sync': 'Sync',
      'export': 'Export',
      'import': 'Import',
      'download': 'Download',
      'upload': 'Upload',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'location': 'Location',
      'gps': 'GPS',
      'enable_location': 'Enable Location',
      'permission_denied': 'Permission Denied',
      'network_error': 'Network Error',
      'server_error': 'Server Error',
      'something_went_wrong': 'Something went wrong',
      'no_internet': 'No Internet Connection',
      'check_connection': 'Please check your internet connection',
      'welcome': 'Welcome',
      'welcome_back': 'Welcome Back',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'good_night': 'Good Night',
      'order_placed': 'Order Placed',
      'order_confirmed': 'Order Confirmed',
      'order_preparing': 'Order Preparing',
      'order_ready': 'Order Ready',
      'order_picked_up': 'Order Picked Up',
      'order_delivered': 'Order Delivered',
      'order_cancelled': 'Order Cancelled',
      'estimated_delivery': 'Estimated Delivery',
      'driver_info': 'Driver Info',
      'call_driver': 'Call Driver',
      'message_driver': 'Message Driver',
      'shop_info': 'Shop Info',
      'menu': 'Menu',
      'products': 'Products',
      'inventory': 'Inventory',
      'staff': 'Staff',
      'promotions': 'Promotions',
      'invoices': 'Invoices',
      'branches': 'Branches',
      'customers': 'Customers',
      'analytics': 'Analytics',
      'reports': 'Reports',
      'sales_report': 'Sales Report',
      'daily_sales': 'Daily Sales',
      'weekly_sales': 'Weekly Sales',
      'monthly_sales': 'Monthly Sales',
      'revenue': 'Revenue',
      'profit': 'Profit',
      'expenses': 'Expenses',
      'tax': 'Tax',
      'discount': 'Discount',
      'coupon': 'Coupon',
      'promo_code': 'Promo Code',
      'enter_promo': 'Enter Promo Code',
      'apply_promo': 'Apply Promo',
      'promo_applied': 'Promo Applied',
      'promo_invalid': 'Invalid Promo Code',
      'promo_expired': 'Promo Code Expired',
      'points': 'Points',
      'loyalty_points': 'Loyalty Points',
      'redeem_points': 'Redeem Points',
      'points_earned': 'Points Earned',
      'points_redeemed': 'Points Redeemed',
      'balance': 'Balance',
      'wallet': 'Wallet',
      'payment': 'Payment',
      'payment_method': 'Payment Method',
      'cash': 'Cash',
      'mobile_money': 'Mobile Money',
      'card': 'Card',
      'bank_transfer': 'Bank Transfer',
      'payment_success': 'Payment Successful',
      'payment_failed': 'Payment Failed',
      'payment_pending': 'Payment Pending',
    },
    'sw': {
      'home': 'Nyumbani',
      'orders': 'Maagizo',
      'profile': 'Wasifu',
      'cart': 'Kikapu',
      'checkout': 'Malipa',
      'login': 'Ingia',
      'signup': 'Jisajili',
      'logout': 'Ondoka',
      'search': 'Tafuta',
      'filter': 'Chuja',
      'sort': 'Panga',
      'price': 'Bei',
      'total': 'Jumla',
      'subtotal': 'Jumla Ndogo',
      'delivery_fee': 'Ada ya Usafirishaji',
      'order_now': 'Agiza Sasa',
      'add_to_cart': 'Ongeza kwenye Kikapu',
      'remove': 'Ondoa',
      'confirm': 'Thibitisha',
      'cancel': 'Ghairi',
      'save': 'Hifadhi',
      'delete': 'Futa',
      'edit': 'Hariri',
      'back': 'Rudi',
      'next': 'Inayofuata',
      'done': 'Imekamilika',
      'loading': 'Inapakia...',
      'error': 'Hitilafu',
      'success': 'Mafanikio',
      'no_data': 'Hakuna data',
      'try_again': 'Jaribu Tena',
      'my_orders': 'Maagizo Yangu',
      'order_history': 'Historia ya Maagizo',
      'track_order': 'Fuatilia Agizo',
      'rate_order': 'Kadiria Agizo',
      'reorder': 'Agiza Tena',
      'favorite_shops': 'Maduka Pendwa',
      'earnings': 'Mapato',
      'map': 'Ramani',
      'history': 'Historia',
      'account': 'Akaunti',
      'available': 'Inapatikana',
      'my_tasks': 'Kazi Zangu',
      'accept_order': 'Kubali Agizo',
      'picked_up': 'Imechukuliwa',
      'delivered': 'Imewasilishwa',
      'navigate': 'Sogeza',
      'online': 'Mtandaoni',
      'offline': 'Nje ya Mtandao',
      'today_earnings': 'Mapato ya Leo',
      'deliveries': 'Usafirishaji',
      'settings': 'Mipangilio',
      'language': 'Lugha',
      'theme': 'Mandhari',
      'dark_mode': 'Mandhari ya Giza',
      'light_mode': 'Mandhari ya Mwanga',
      'swahili': 'Kiswahili',
      'english': 'Kiingereza',
      'notifications': 'Arifa',
      'help': 'Msaada',
      'about': 'Kuhusu',
      'contact': 'Wasiliana',
      'phone': 'Simu',
      'email': 'Barua pepe',
      'address': 'Anwani',
      'name': 'Jina',
      'password': 'Nenosiri',
      'forgot_password': 'Umesahau Nenosiri?',
      'reset_password': 'Weka Nenosiri Jipya',
      'change_password': 'Badilisha Nenosiri',
      'update_profile': 'Sasisha Wasifu',
      'view_all': 'Tazama Yote',
      'see_more': 'Ongeza',
      'see_less': 'Punguza',
      'read_more': 'Soma Zaidi',
      'close': 'Funga',
      'open': 'Fungua',
      'closed': 'Imefungwa',
      'rating': 'Kadirio',
      'reviews': 'Maoni',
      'write_review': 'Andika Maoni',
      'submit': 'Wasilisha',
      'share': 'Shiriki',
      'copy': 'Nakili',
      'paste': 'Bandika',
      'select': 'Chagua',
      'select_all': 'Chagua Yote',
      'clear': 'Futa',
      'apply': 'Tumia',
      'reset': 'Weka Upya',
      'refresh': 'Onyesha Upya',
      'sync': 'Sawazisha',
      'export': 'Hamisha',
      'import': 'Ingiza',
      'download': 'Pakua',
      'upload': 'Pakia',
      'camera': 'Kamera',
      'gallery': 'Matunzio',
      'location': 'Mahali',
      'gps': 'GPS',
      'enable_location': 'Washa Mahali',
      'permission_denied': 'Ruhusa Imekataliwa',
      'network_error': 'Hitilafu ya Mtandao',
      'server_error': 'Hitilafu ya Seva',
      'something_went_wrong': 'Hitilafu Imetokea',
      'no_internet': 'Hakuna Mtandao',
      'check_connection': 'Tafadhali angalia muunganisho wako',
      'welcome': 'Karibu',
      'welcome_back': 'Karibu Tena',
      'good_morning': 'Habari ya Asubuhi',
      'good_afternoon': 'Habari ya Mchana',
      'good_evening': 'Habari ya Jioni',
      'good_night': 'Usiku Mwema',
      'order_placed': 'Agizo Limewekwa',
      'order_confirmed': 'Agizo Limethibitishwa',
      'order_preparing': 'Agizo Linaandaliwa',
      'order_ready': 'Agizo Liko Tayari',
      'order_picked_up': 'Agizo Limechukuliwa',
      'order_delivered': 'Agizo Limewasilishwa',
      'order_cancelled': 'Agizo Limeghairiwa',
      'estimated_delivery': 'Makadirio ya Usafirishaji',
      'driver_info': 'Maelezo ya Dereva',
      'call_driver': 'Piga Simu Dereva',
      'message_driver': 'Tuma Ujumbe Dereva',
      'shop_info': 'Maelezo ya Duka',
      'menu': 'Menyu',
      'products': 'Bidhaa',
      'inventory': 'Hifadhi',
      'staff': 'Wafanyakazi',
      'promotions': 'Matangazo',
      'invoices': 'Ankara',
      'branches': 'Tawi',
      'customers': 'Wateja',
      'analytics': 'Uchambuzi',
      'reports': 'Ripoti',
      'sales_report': 'Ripoti ya Mauzo',
      'daily_sales': 'Mauzo ya Kila Siku',
      'weekly_sales': 'Mauzo ya Kila Wiki',
      'monthly_sales': 'Mauzo ya Kila Mwezi',
      'revenue': 'Mapato',
      'profit': 'Faida',
      'expenses': 'Matumizi',
      'tax': 'Kodi',
      'discount': 'Punguzo',
      'coupon': 'Kuponi',
      'promo_code': 'Msimbo wa Promosheni',
      'enter_promo': 'Weka Msimbo',
      'apply_promo': 'Tumia Promosheni',
      'promo_applied': 'Promosheni Imetumika',
      'promo_invalid': 'Msimbo Batili',
      'promo_expired': 'Msimbo Umeisha',
      'points': 'Pointi',
      'loyalty_points': 'Pointi za Uaminifu',
      'redeem_points': 'Komboa Pointi',
      'points_earned': 'Pointi Zilizopatikana',
      'points_redeemed': 'Pointi Zilizokombwa',
      'balance': 'Salio',
      'wallet': 'Mkoba',
      'payment': 'Malipo',
      'payment_method': 'Njia ya Malipo',
      'cash': 'Fedha Taslimu',
      'mobile_money': 'Pesa ya Simu',
      'card': 'Kadi',
      'bank_transfer': 'Uhamisho wa Benki',
      'payment_success': 'Malipo Yamefanikiwa',
      'payment_failed': 'Malipo Yameshindikana',
      'payment_pending': 'Malipo Yanasubiri',
    },
  };

  static String translate(String key, {String language = 'en'}) {
    return _translations[language]?[key] ?? _translations['en']?[key] ?? key;
  }

  static String t(String key, {String language = 'en'}) {
    return translate(key, language: language);
  }
}

class LanguageService extends ChangeNotifier {
  String _currentLanguage = 'en';

  String get currentLanguage => _currentLanguage;

  String t(String key) => AppLocalizations.t(key, language: _currentLanguage);

  Future<void> setLanguage(String lang) async {
    if (_translations.containsKey(lang)) {
      _currentLanguage = lang;
      notifyListeners();
    }
  }

  void toggleLanguage() {
    _currentLanguage = _currentLanguage == 'en' ? 'sw' : 'en';
    notifyListeners();
  }

  bool get isSwahili => _currentLanguage == 'sw';

  static const Map<String, Map<String, String>> _translations =
      AppLocalizations._translations;
}
